version: '3.8'
services:
  app:
    build:
      context: .
    container_name: trader_app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=trader
      - DB_PASSWORD=trader
      - DB_NAME=trader
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - trader_network

  db:
    build:
      context: ./mysql
    container_name: trader_mysql
    environment:
      MYSQL_ROOT_PASSWORD: trader
      MYSQL_DATABASE: trader
      MYSQL_USER: trader
      MYSQL_PASSWORD: trader
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/tbl-csv:/var/lib/mysql-files
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --sql-mode="NO_ENGINE_SUBSTITUTION" --explicit_defaults_for_timestamp
    networks:
      - trader_network

volumes:
  db_data:

networks:
  trader_network:
